export const DAILY_MATCH_LOAD = 'DAILY_MATCH_LOAD';
export const DAILY_MATCH_SUCCESS = 'DAILY_MATCH_SUCCESS';
export const DAILY_MATCH_ERROR = 'DAILY_MATCH_ERROR';

export const LIVE_MATCH_LOAD = 'LIVE_MATCH_LOAD';
export const LIVE_MATCH_SUCCESS = 'LIVE_MATCH_SUCCESS';
export const LIVE_MATCH_ERROR = 'LIVE_MATCH_ERROR';

export const MATCHES_LOAD = 'MATCHES_LOAD';
export const MATCHES_SUCCESS = 'MATCHES_SUCCESS';
export const MATCHES_ERROR = 'MATCHES_ERROR';
