export const DAILY_MATCH_LOAD = 'DAILY_MATCH_LOAD';
export const DAILY_MATCH_SUCCESS = 'DAILY_MATCH_SUCCESS';
export const DAILY_MATCH_ERROR = 'DAILY_MATCH_ERROR';

export const LIVE_MATCH_LOAD = 'LIVE_MATCH_LOAD';
export const LIVE_MATCH_SUCCESS = 'LIVE_MATCH_SUCCESS';
export const LIVE_MATCH_ERROR = 'LIVE_MATCH_ERROR';
